---

- name: Define php_packages
  set_fact:
    php_packages: "{{ __php_packages | list }}"
  when: php_packages is not defined

- name: Define php_webserver_daemon
  set_fact:
    php_webserver_daemon: "{{ __php_webserver_daemon }}"
  when: php_webserver_daemon is not defined

- name: Define php_conf_paths
  set_fact:
    php_conf_paths: "{{ __php_conf_paths }}"
  when: php_conf_paths is not defined

- name: Define php_extension_conf_paths
  set_fact:
    php_extension_conf_paths: "{{ __php_extension_conf_paths }}"
  when: php_extension_conf_paths is not defined

- name: Ensure PHP packages are installed
  yum:
    name: "{{ item }}"
    state: "{{ php_packages_state }}"
    enablerepo: "{{ php_enablerepo }}"
  with_items: "{{ php_packages }}"
  notify: restart webserver

- include: php-config.yml
